version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "deps"
      include: "scope"
    reviewers:
      - "HanielCota"
    ignore:
      - dependency-name: "org.projectlombok:lombok"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "com.velocitypowered:velocity-api"
        update-types: ["version-update:semver-major"]