changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
      - github-actions
  categories:
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
    - title: Security
      labels:
        - security
    - title: Maintenance
      labels:
        - dependencies
        - documentation
        - chore
    - title: Other Changes
      labels:
        - '*'
